CREATE TABLE IF NOT EXISTS users  (
  id SERIAL PRIMARY KEY,
  username VARCHAR(20) UNIQUE,
  password VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS user_scores (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  game_id INTEGER REFERENCES games(id),
  score INTEGER NOT NULL CHECK(score >= 0 AND score <= 100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
